# Generated by Django 4.2.1 on 2023-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('partner', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('description', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('donation_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.event')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(through='pos.TransactionItem', to='pos.item'),
        ),
    ]
