# Generated by Django 4.2.1 on 2023-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash',
            field=models.BooleanField(default=True),
        ),
    ]
