# Generated by Django 4.2.1 on 2023-05-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_event_org_transaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.organization'),
        ),
    ]
