# Generated by Django 4.2.1 on 2023-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_item_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
