# Generated by Django 4.2.1 on 2023-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_event_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='HVGB', max_length=10),
            preserve_default=False,
        ),
    ]
