# Generated by Django 4.2.1 on 2023-05-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_organization_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.organization'),
        ),
    ]
