# Generated by Django 4.2.1 on 2023-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_userinfo_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
